frontend/src/App.css, frontend/src/pages/Explore.jsx, package-lock.json
Optimized the Search section UI and added the .popular-searches-section class in the App.css file to improve the visual appearance. I'm excited to contribute to this open-source project, as I truly love the idea behind it.
Before
After
=> search section UI optimized 

frontend/package-lock.json, frontend/package.json, frontend/src/components/Footer.jsx, frontend/src/pages/about.jsx, frontend/src/routes/AppRoutes.jsx
- Created About Us page
- Made footer height and layout more professional
- Cleaned up unused icons and aligned with latest design decisions
- Footer links are now functional and redirect appropriately.
https://drive.google.com/file/d/1ko230egjo-Nsu6HdO59Et7-GpkGPqBPJ/view?usp=drive_link
#16
=> Fixed footer links and added about us page

frontend/src/App.css, frontend/src/App.jsx, frontend/src/components/Navbar.jsx
This PR adds comprehensive dark mode support to the Pouranik website with a toggle button and persistent user preferences.
- Added to navbar for easy access
- Sun/moon icons for light/dark modes
- Mobile-responsive (icon-only on small screens)
- Remembers user preference with localStorage
- Auto-detects system preference on first visit
- Complete dark theme using CSS custom properties
- Enhanced text contrast for all elements
- Improved button visibility and readability
- Better icon contrast with shadows
- Smooth 0.3s transitions between themes
- Navbar with toggle functionality
- Footer text visibility improvements
- Book card background fixes for text readability
- Genre page element styling
- Button contrast enhancements
- Icon visibility improvements
- Uses CSS custom properties for …
=> feat: Add dark mode support with theme toggle

frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/components/Footer.jsx, frontend/src/components/Navbar.jsx, frontend/src/index.css, frontend/src/pages/Explore.jsx, frontend/src/pages/Explore.module.css, frontend/src/pages/Genres.css, frontend/src/pages/Genres.jsx, frontend/src/pages/Home.jsx
1. Replaced hardcoded emojis with react icons :
- Imported icons from lucide-react
- Replaced hardcoded emojis with React icons
- Added appropriate styling and sizing
2. Hamburger Menu for Mobile Navigation 
- Added mobile menu state management and toggle functionality
- Created mobile menu overlay and content components
- Styled mobile menu for theme consistency
3. Fixed homepage elements 
- Redundant animations with aesthetic ones that don't persist after page has been loaded 
- Card size fix 
- css refactoring with migrating to standalone css instead of inline css for homepage 
Fixes [Issue] #41 
@BhaktiMore18  @Rohansingh3001 
1. Screenshot of Mobile view 
2. Video Recording of New look
https://github.com/user-attachments/assets/b6dc6967-f200-4a96-b64b-ecf7736d5067
=> Fix Mobile Responsiveness and Home Page

frontend/src/pages/Explore.jsx
screenshot-
fixes #85 
Please let me know if any further changes are required.
=> fixed authors logic in explore books section

frontend/src/pages/Explore.jsx
Previously we were not able to change the search bar once it was filled using any tag or genre
The bug is now fixed
#67
=> fixed the bug of explore search bar

frontend/src/components/BookCard.jsx
=> resolved display bug

frontend/src/App.jsx, frontend/src/components/AuthForm.jsx, frontend/src/pages/SignIn.jsx, frontend/tailwind.config.js
screenshot-
FIXES #87 
please let me know if any further changes are required
=> fixed dark mode in signup/signin get started page

frontend/package.json, frontend/src/App.css, frontend/src/App.jsx, frontend/src/components/AuthForm.jsx, frontend/src/components/Navbar.jsx, frontend/src/pages/SignIn.jsx, frontend/src/routes/AppRoutes.jsx
Here changes i made : #83  ui bugs and enhancement
1. Navbar "Get Started" Button - Active State Highlight
Applied route check using isActive to the "Get Started" button in Navbar.jsx
Now consistently highlights when the route is active, like other nav links
2. Broken Email Input Field in AuthForm
Fixed the broken layout of the email input field in AuthForm.jsx(the form ui will works on the dark and light mode both ensure that)
Adjusted padding, width, and borders for a cleaner and more usable input experience
3. Review of Temporary Registered Users Array (No Change Needed)
Initially planned to add a local array for mock user data during development
Upon review, realized the app already sends data directly to the backend
No need for an additional array or collection — left this logic …
=> UI Bugs & Enhancements

frontend/src/components/Footer.jsx
Hi team 👋
As discussed with the maintainers, this PR focuses solely on fixing the **footer design inconsistency** highlighted in #102 
---
1. **Footer Color Overhaul**
* Removed the dark bluish gradient (`#1d2739 → #121a2d`)
* Applied a **white/green theme** to better align with the app’s primary light-mode color scheme
2. **Design Consistency**
* Added standard footer elements: logo, links, and social icons
* Matched typography and spacing with the rest of the platform
---
Before:
After:
---
`gssoc2025`
`level 3`
Thanks!
Deepanshu Prajapati
---
Let me know if you'd like a shortened version or a version with GitHub markdown badges or task list.
=> Footer Color Inconsistency & Responsive Improvements - Closes #102

frontend/src/pages/Home.jsx
Before Update[BUG]:-
When someone click on chatbot widget it will open ,but then someone try to close chatbox it not closed.
Not Open  ----->  Clicked  ----->  Open
Open         ------> Clicked ------> Not closed
After Update:-
Not Open  ----->  Clicked  ----->  Open
Open         ------> Clicked ------>  Closed
It was a very interesting experience working on this project. This was my first open source contribution, and I truly enjoyed the process. I'm looking forward to exploring more opportunities and growing further in the open source world!
https://github.com/user-attachments/assets/d83f5f74-d703-4cbe-ac4a-169069fd9a17
=> #122 add toggel functionality in chatbot widget

frontend/src/components/Footer.jsx
Updated the footer background to a soft teal shade (`#ccfbf1`) and adjusted text color to `gray-600` for improved readability and visual harmony with the rest of the layout in light mode.
Fixes: #128 
- Replaced the old background with `#ccfbf1` using Tailwind utility: `!bg-[#ccfbf1]`
- Set text color to `gray-600` for better contrast against the new background
- Retained existing padding and structure (`pt-12 pb-6`)
The background change was tested to ensure it looks consistent in light mode and dark mode.
Before--
The readablity is less in dark mode (Before)
After 
Light Mode--
Dark Mode--
---
=> enhanced the footer section background in modes

frontend/src/App.css, frontend/src/components/SearchAutocomplete.jsx, frontend/src/pages/Explore.jsx, frontend/src/pages/Explore.module.css
now :
before 
closes : #137 
please merge and assign also with appropriate level @BhaktiMore18
=> fixed css of explore page

frontend/src/components/AuthForm.jsx
Changed the UI of login button to make it visible
=> updated login button

frontend/src/components/AuthForm.jsx, frontend/src/components/Footer.jsx, frontend/src/components/Navbar.jsx, frontend/src/pages/SignIn.jsx
Adding style navbar size footer text-color.
Fixes issue #150
=> Style navbar size, login and signup text-color

frontend/src/pages/Genres.css, frontend/src/pages/Genres.jsx
1. This PR introduces visually enhanced borders to clearly separate different sections of the website.
2. Added stylish gradient/teal borders with thickness variation (thin at the ends, thicker in the middle) for a modern look.
3. Improves section distinction for better readability and structure.
4. Enhances the overall UI/UX aesthetic while keeping the design consistent with the website’s theme.
Before--
After--
🔗 Additional Info
The changes are purely visual and do not affect the functionality of any section. They help users visually navigate through different content areas more easily.
=> separating different sections with fancy border

frontend/src/App.css, frontend/src/components/Navbar.jsx
Fixed nav links background color on dark mode to make it look aesthetically more pleasing.
fixes #176
closes #176
=> Fixed nav-links background color on dark mode

README.md
This PR introduces a detailed Project Structure section to the README.md file for the Pouranik repository. The updated structure provides a clear, commented directory tree covering both backend and frontend, improving clarity for contributors and users.
- Documentation update
- Fixes [ #198 ]
=> Add project structure in Readme.md

frontend/src/App.css, frontend/src/components/AuthForm.jsx
- Improved **Contact Form heading** with a teal-themed gradient + glow effect for better visibility.  
- Enhanced **border & background contrast** in dark mode for clearer separation of form sections.  
- Optimized text readability in dark mode with appropriate color choices.  
- Added subtle shadows and highlights to make the form more visually appealing.  
This PR enhances the **overall dark mode experience** of the Contact Form, ensuring:  
- Better readability  
- More consistent teal-themed styling  
- A modern, user-friendly UI  
Users will now experience a **polished, accessible, and visually cohesive** Contact Form in dark mode.  
Screenshots--
Before--
After--
---
Fixes Issue : #196
=> Enhance Contact Form in Dark Mode  

frontend/src/components/Notfound.jsx, frontend/src/routes/AppRoutes.jsx
https://github.com/user-attachments/assets/148f8ac7-d2f7-4c01-8225-94092b202d6b
please check added not found page for both dark and light mode
=> notfound page 
